### ISSUE TITLE
Filter doesn't show up in the filter menu

### ISSUE THREAD

**Issue by typoman** [mekkablue/Disguiser#3]
Glyphs app Version 2.6.2 (1239)

**Comment by mekkablue** [comment]
Cannot reproduce in 2.6.2 (1239) on Mojave:

![Captura de Pantalla 2019-05-20 a la(s) 11 35 42](https://user-images.githubusercontent.com/1103103/58011834-6c0ddc00-7af3-11e9-81f5-59d48502a1a4.png)

Must be a different problem. Try disabling all other plug-ins, and de- and re-installing Disguiser through the Plugin Manager, then restart. And watch out for error messages in the Macro Window and Console.app (search for "Disguiser" or "Glyphs").

**Comment by typoman** [comment]
I did all you described and I get this:
`Glyphs[791]: Disguiser has encountered a fatal error, and will now terminate.
`
This is from Console.app
